#!/usr/bin/env python3
"""check_links.py - summarize data/enrichment.json and write data/_dead.md for a human look.

Prints per-status counts (ok / redirected / dead / manual_ok) and lists everything that is not plain 'ok'
with id, name, url, http status and final url. Exit code is always 0 - tools/lint.py is the gate.
Run from the repo root after tools/enrich.py: python3 tools/check_links.py
"""
import csv
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LINKS = os.path.join(ROOT, "data", "links.csv")
ENRICH = os.path.join(ROOT, "data", "enrichment.json")
DEAD = os.path.join(ROOT, "data", "_dead.md")


def main():
    if not os.path.exists(ENRICH):
        sys.exit("missing data/enrichment.json - run tools/enrich.py first")
    with open(ENRICH, encoding="utf-8") as f:
        enrich = json.load(f)
    names = {}
    if os.path.exists(LINKS):
        with open(LINKS, newline="", encoding="utf-8") as f:
            for r in csv.DictReader(f):
                names[r["id"]] = r
    counts = {"ok": 0, "redirected": 0, "dead": 0, "manual_ok": 0}
    groups = {"dead": [], "redirected": [], "manual_ok": []}
    for eid, rec in sorted(enrich.items()):
        st = rec.get("status", "dead")
        counts[st] = counts.get(st, 0) + 1
        if st in groups:
            groups[st].append((eid, rec))
    last = max((r.get("last_checked", "") for r in enrich.values()), default="")
    print("links checked: %d (last check %s)" % (len(enrich), last or "never"))
    for k in ("ok", "redirected", "dead", "manual_ok"):
        print("  %-10s %d" % (k, counts.get(k, 0)))

    L = ["# Link check", "", "Generated by `tools/check_links.py` from `data/enrichment.json` (last check %s)." % (last or "never"),
         "Fix a dead link by setting `url` in `data/overrides.json` for that id, or remove the link at the source (Notion).", "",
         "Counts: " + ", ".join("%s %d" % (k, counts.get(k, 0)) for k in ("ok", "redirected", "dead", "manual_ok")), ""]
    titles = {"dead": "## Dead (lint fails on these)", "redirected": "## Redirected (final URL differs; GitHub renames are auto-fixed in the README)",
              "manual_ok": "## Needs a human look (bot-blocked host, login wall or server error)"}
    for key in ("dead", "redirected", "manual_ok"):
        L.append(titles[key])
        L.append("")
        if not groups[key]:
            L.append("- none")
        for eid, rec in groups[key]:
            row = names.get(eid, {})
            name = row.get("name", "?")
            sec = row.get("section", "") + (" / " + row["subsection"] if row.get("subsection") else "")
            line = "- `%s` %s - %s (%s) - http %s" % (eid, name, rec.get("url", ""), sec, rec.get("http_status", 0))
            if rec.get("final_url") and rec.get("final_url") != rec.get("url"):
                line += " -> " + rec["final_url"]
            if rec.get("error"):
                line += " - " + str(rec["error"])[:120]
            L.append(line)
        L.append("")
    also_bad = []
    for eid, rec in sorted(enrich.items()):
        for u, st in sorted((rec.get("also") or {}).items()):
            if st.get("status") == "dead":
                also_bad.append((eid, u, st))
    L.append("## Secondary links that failed (dropped from the README's 'also:' links)")
    L.append("")
    if not also_bad:
        L.append("- none")
    for eid, u, st in also_bad:
        row = names.get(eid, {})
        L.append("- `%s` %s - %s - http %s%s" % (eid, row.get("name", "?"), u, st.get("http_status", 0),
                                                 " - " + str(st.get("error", ""))[:100] if st.get("error") else ""))
    L.append("")
    with open(DEAD, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("wrote data/_dead.md")


if __name__ == "__main__":
    main()
